<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Airlock</RootNamespace>
    <AssemblyName>Airlock.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CShell" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Airlock.Core.Tests" />
  </ItemGroup>

</Project>
